[package]
name = "pfact"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "4.4.8"
feature = "0.5.1"
num = "0.4.1"
num_cpus = "1.16.0"

[dev-dependencies]
assert_cmd = "2.0.12"